### PR TITLE
Auth email

### PR DESCRIPTION
**Pull request by HelenaWu**
Hey Eliot,  
  Happy holidays!!  
  I began the Blocmetrics assignment trying to implement authentication from scratch, however the code is running into a few issues including design confusions for coding the confirmation email and unable to send email from my localhost mailer. It would be great to go over this during our call tomorrow, thank you!  

Warm regards,  
Helena

### CODE REVIEW

**Comment by HelenaWu** [comment]
Also please don't mark Blocpedia as complete yet, upon a second running the collaborator autocomplete function wasn't working again. I will work on fixing that in the coming week. :)

**Comment by eliotsykes** [comment]
@HelenaWu Take a look at Rails' built-in `has_secure_password` method. Its ok you've not used it here (it wasn't available when the screencast was made) but its good to be aware of it: http://api.rubyonrails.org/classes/ActiveModel/SecurePassword/ClassMethods.html#method-i-has_secure_password

**Comment by HelenaWu** [comment]
Hey Eliot,  
  I took a look at the has_secure_password method, this is just a substitute for validation for existence and confirmation?  (code below)

```
validates_confirmation_of :password
validates_presence_of :password, :on => :create
```

**Comment by eliotsykes** [comment]
@HelenaWu It does those validations _and_ does the hashing of the original password using bcrypt.

**Pull request merged**
